const ADMIN_ROLE = "admin";
const MERCHANT_ROLE = "merchant";
const USER_ROLE = "user";
const PUBLIC_ROLE = "anonymous-user";
const ROLES = [ADMIN_ROLE, MERCHANT_ROLE, USER_ROLE];
const AUTH_ROLES = [ADMIN_ROLE, MERCHANT_ROLE, USER_ROLE, PUBLIC_ROLE];

const SUCCESS_REQUEST = 200;
const CREATED_OR_UPDATED_SUCCESS = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED_REQUEST = 401;
const FORBIDDEN_REQUEST = 403;
const NOT_FOUND_REQUEST = 404;
const SERVER_ERROR_REQUEST = 500;

const REQUEST = {
  SUCCESS: SUCCESS_REQUEST,
  UPDATED: CREATED_OR_UPDATED_SUCCESS,
  CREATED: CREATED_OR_UPDATED_SUCCESS,
  BAD_REQUEST: BAD_REQUEST,
  UNAUTHORIZED: UNAUTHORIZED_REQUEST,
  FORBIDDEN: FORBIDDEN_REQUEST,
  NOT_FOUND: NOT_FOUND_REQUEST,
  INTERNAL_SERVER_ERROR: SERVER_ERROR_REQUEST,
};

module.exports = {
  ADMIN_ROLE,
  MERCHANT_ROLE,
  USER_ROLE,
  PUBLIC_ROLE,
  ROLES,
  AUTH_ROLES,
  REQUEST,
};
